### ISSUE TITLE
Create Pull Request templates

### ISSUE THREAD

**Issue by rosariopfernandes** [rosariopfernandes/NotDog#14]
Some recent Pull Requests have not followed our [Contributing Guidelines](CONTRIBUTING.md). I think we should create a PR template with a checklist that contributors need to fill when sending a PR.

Example Checklist:
- [ ] I have read the [Contributing Guidelines](CONTRIBUTING.md)
- [ ] I have discussed these changes via issue
- [ ] I have made my changes on a new branch

Feel free to add more items to the checklist.

**Comment by EdNgulele** [comment]
I'd love work on this. Please assign me.

**Comment by rosariopfernandes** [comment]
@EdNgulele Sure, go ahead. [Here's an example](https://github.com/sendgrid/sendgrid-java/blob/master/.github/PULL_REQUEST_TEMPLATE) you can use.

**Comment by EdNgulele** [comment]
Thank you! What do you think about adding another template for issues? Please take a look at [these templates](https://github.com/stevemao/github-issue-templates)

**Comment by rosariopfernandes** [comment]
@EdNgulele Doesn't seem necessary so far. But if we ever need it, I will come back to you. Let's stick to a PR template only.

**Comment by EdNgulele** [comment]
@rosariopfernandes Where do you prefer to have the PR template stored? Do you want it to be visible in the  **repository's root** directory, visible in the **repository's docs** or in a **hidden directory**, such as _.github/_?

**Comment by rosariopfernandes** [comment]
I think `.github/` is the best option
