### ISSUE TITLE
[TYPO] Contributing Guidelines referencing a different repository 

### ISSUE THREAD

**Issue by EdNgulele** [rosariopfernandes/NotDog#23]
I was looking at the [Contributing Guidelines
](https://github.com/rosariopfernandes/NotDog/blob/master/CONTRIBUTING.md) and I noticed that on the [Pull Request](https://github.com/rosariopfernandes/NotDog/blob/master/CONTRIBUTING.md#pull-requests) and [Sending Pull Requests
](https://github.com/rosariopfernandes/NotDog/blob/master/CONTRIBUTING.md#sending-pull-requests) sections you're giving instructions to contribute in a different repository, [fireXtensions](https://github.com/rosariopfernandes/fireXtensions), instead of NotDog. 

I will send a PR correcting this. I will change:

1. `github.com/rosariopfernandes/firextensions/issues/new` to `https://github.com/rosariopfernandes/NotDog/issues/new`

2. `git remote add upstream https://github.com/rosariopfernandes/firextensions` to `git remote add upstream https://github.com/rosariopfernandes/NotDog `

**Comment by rosariopfernandes** [comment]
Ahh, copy paste issues. Thanks @EdNgulele
